language: cpp

os:
  - linux

compiler:
  - gcc
env:
  global:
    - OMP_NUM_THREADS=4
    - N_THREADS=4
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - gcc-4.8
    - g++-4.8
    - libgtest-dev

cache:
  - apt

before_install:
  - # setup compiler to GCC 4.8
  - export CC=/usr/bin/gcc-4.8
  - export CXX=/usr/bin/g++-4.8
  - $CXX --version

  - # install Cmake 3.5
  - cmake --version
  - export CMAKE_VERSION=`cmake --version | grep  -oP '\d.\d.\d'`
  - if [ "$CMAKE_VERSION" != "3.5.2" ]; then
      wget --no-check-certificate https://www.cmake.org/files/v3.5/cmake-3.5.2.tar.gz ;
      tar xf cmake-3.5.2.tar.gz ;
      cd cmake-3.5.2 ;
      ./configure ;
      make -j4 ;
      sudo make install ; 
      cd ../ ; 
      rm -rf ./cm* ; 
      cmake --version ;
      fi

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=BUILD_TYPE                          
    -DCMAKE_CXX_FLAGS="-std=c++11 -Wl -Wall -pedantic -fno-rtti" 
    -DCMAKE_CXX_FLAGS_DEBUG="-g"                                 
    -DCMAKE_CXX_FLAGS_RELEASE="-O3 -DNDEBUG -std=c++11"          
    -DCMAKE_EXE_LINKER_FLAGS_RELEASE="-flto"                     
    ..

script: 
  - make -j4 && ctest --output-on-failure
