language: cpp

os:
  - linux

compiler:
  - gcc
env:
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - gcc-4.8
      - g++-4.8
      - libgsl0ldbl
      - libgtest-dev
      - libgsl0-dev
      - valgrind


install:
  - sudo apt-get install lcov rubygems
  - gem install lcoveralls

cache:
  - apt
  - pip

before_install:
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
  - export PATH=$PATH:/usr/local/bin/
  - export CC=/usr/bin/gcc-4.8
  - export CXX=/usr/bin/g++-4.8


before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=BUILD_TYPE
    -DCMAKE_CXX_FLAGS="-std=c++11 -Wall -pedantic -fno-rtti -fprofile-arcs -ftest-coverage"
    -DCMAKE_CXX_FLAGS_DEBUG="-g"
    -DCMAKE_CXX_FLAGS_RELEASE="-Ofast -DNDEBUG -march=native"
    -DCMAKE_EXE_LINKER_FLAGS="--coverage"
    -DCMAKE_EXE_LINKER_FLAGS_RELEASE="-flto"
    ..

script:
  - make -j4
  - ctest -VV

after_success:
 - lcov --capture --directory .. --output-file coverage.info
 - cat coverage.info
 - lcoveralls --root .. -v
 - ./TC1_Acceleration --threads 4
