sudo: false
language: cpp

os:
  - linux

compiler:
  - gcc
env:
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release
  global:

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
      - libreoffice/libreoffice-4-2
    packages:
      - cmake
      - cmake-data
      - gcc-4.8
      - g++-4.8
      - libgsl0ldbl
      - libgtest-dev
      - libgsl0-dev
      - valgrind
      - gcov-4.8
      - lcov
      - doxygen
      - graphviz

install:
  - pip install --user cpp-coveralls

cache:
  - apt
  - pip

before_install:
  - export CC=/usr/bin/gcc-4.8
  - export CXX=/usr/bin/g++-4.8

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=BUILD_TYPE ..
    #-DCMAKE_CXX_FLAGS_RELEASE="-Ofast -DNDEBUG -march=native"
    #-DCMAKE_EXE_LINKER_FLAGS_RELEASE="-flto"
    #..

script:
  - make -j4 VERBOSE=1
  - ctest -VV

after_success:
 - coveralls --help
 - coveralls --gcov gcov-4.8  --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*unit-tests/.*.cpp.*" -E "/usr/include/.*"
 - ./TC1_Acceleration --threads 4
 - if [ "$BUILD_TYPE" == "Debug" ]; then
     cd ../ ;
     doxygen Doxyfile ;
     export BUILD_PATH=`pwd` ;
     cd "$TRAVIS_BUILD_DIR" ;
     git clone --branch=gh-pages --recursive https://github.com/kiliakis/BLonD-minimal-cpp.git web ;
     cd web ;
     cp -rf $BUILD_PATH/documentation/html/* ./ ;
     git add -A ;
     git -c user.name='travis' -c user.email='travis' commit -am "documentation update" ;
     git push -f -q https://kiliakis:$GITHUB_API_KEY@github.com/kiliakis/BLonD-minimal-cpp.git gh-pages ;
   fi

