language: cpp

os:
  - linux

compiler:
  - gcc
env:
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - gcc-4.8
      - g++-4.8
      - libgsl0ldbl
      - libgtest-dev
      - libgsl0-dev
      - valgrind
      - gcov-4.8

install:
  - pip install cpp-coveralls

cache:
  - apt
  - pip

before_install:
  - export CC=/usr/bin/gcc-4.8
  - export CXX=/usr/bin/g++-4.8

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=BUILD_TYPE
    -DCMAKE_CXX_FLAGS_RELEASE="-Ofast -DNDEBUG -march=native"
    -DCMAKE_EXE_LINKER_FLAGS_RELEASE="-flto"
    ..

script:
  - make -j4
  - ctest -VV

after_success:
 - if [ "${BUILD_TYPE}" = "Debug" ]; then
      coveralls --verbose --gcov gcov-4.8  --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*unit-tests/.*.cpp.*"
   fi
 - ./TC1_Acceleration --threads 4
