language: cpp

os:
  - linux

compiler:
  - gcc
env:
  global:
    - OMP_NUM_THREADS=4
    - N_THREADS=4
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - gcc-4.8
    - g++-4.8
    - libgtest-dev

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=BUILD_TYPE      \
    -DCMAKE_CXX_FLAGS="-std=c++11 -Wl -Wall -pedantic -fno-rtti"           \
    -DCMAKE_CXX_FLAGS_DEBUG="-g"             \
    -DCMAKE_CXX_FLAGS_RELEASE="-O3 -DNDEBUG -std=c++11" \
    -DCMAKE_EXE_LINKER_FLAGS_RELEASE="-flto" \
    ..

script: 
  - make -j4 && ctest --output-on-failure
