#note: OpenCL instructions taken from  https://github.com/ddemidov/vexcl/blob/master/.appveyor.yml
environment:
  matrix:
    - VSVER: Visual Studio 14 2015
    - VSVER: Visual Studio 14 2015 Win64
  global:
    INTELOCLSDKROOT: "C:/Program Files (x86)/Intel/OpenCL SDK/5.3"

cache: 
  - C:\ProgramData\chocolatey\bin -> appveyor.yml 
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

configuration:
  - Debug
  - Release

install:
  - git submodule update --init --recursive
  - choco install -y doxygen.portable swig > null

before_build:
  - mkdir build
  - cd build
  - cmake -DOPENCL_SDK_PATH="%INTELOCLSDKROOT%" -DBUILD_EXTERNALS=True ..
  - DIR

#build: of
build_script:
  - cmake --build . --target ALL_BUILD --config %CONFIGURATION% -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

#test_script:
#  - ctest -VV
