environment:
  matrix:
    - VSVER: Visual Studio 14 2015 Win64

install:
  - choco install cmake
  - choco upgrade cmake
  #- cd external
  #- cd gsl
  #- cmake .
  #- DIR
  #- msbuild GSL.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cd ../
  - cd googletest
  - cmake .
  - DIR 
  - msbuild gtest.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

cache: 
  - C:\ProgramData\chocolatey\bin -> appveyor.yml 
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

configuration:
  - Debug
  - Release

build:
  project: BLonD.sln

