environment:
  matrix:
    - VSVER: Visual Studio 14 2015 Win64

cache: 
  - C:\ProgramData\chocolatey\bin -> appveyor.yml 
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

configuration:
  - Debug
  - Release

install:
  - choco install cmake
  - choco upgrade cmake
  - git submodule update --init --recursive
  - DIR external\gsl
  - DIR external\gsl\contrib

before_build:
  - mkdir build
  - cd build
  - cmake ..
  - DIR

build_script::
  - cmake --build .. -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
  - ctest -VV
