environment:
  matrix:
    - VSVER: Visual Studio 14 2015 Win64

install:
  - choco install cmake
  - choco upgrade cmake
  - mkdir build
  - cd build
  - cmake ..
  - DIR
  - msbuild BLonD-minimal-cpp.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

cache: 
  - C:\ProgramData\chocolatey\bin -> appveyor.yml 
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

configuration:
  - Debug
  - Release

